services:
  extrinsic_calibration:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    user: "ada"
    working_dir: /home/ada
    network_mode: host

    init: true
    privileged: true

    environment:
      - DISPLAY=$DISPLAY

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/ros_ws/src/

    stdin_open: true
